name: Bump version and create a new release
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    types:
      - labeled
jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Bumps version on merging Pull Requests with specific labels.
      # (bump:major, bump:minor, bump:patch)
      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      - uses: haya14busa/action-update-semvar@v1
        if: "!steps.bumpr.outputs.skip"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bumpr.outputs.next_version }}

      # Build a change log
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a release with the latest bumped version
      - name: Create a releae
        uses: technote-space/release-github-actions@v6

  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
